package com.example.model

enum class TestType(val displayName: String, val badge: String, val description: String) {
    CHAPTER("Chapter Test", "Chapter Sprint", "Deep dive into a single chapter to verify fundamental mastery"),
    SUBJECT("Subject Test", "Subject Diagnostic", "Comprehensive coverage of all chapters in a single subject"),
    CURRICULUM("Curriculum Test", "Curriculum Benchmark", "Mid-term and cumulative milestones aligned with syllabus"),
    NCERT_ALIGNED("NCERT-Aligned Test", "NCERT Line-by-Line", "Strict NCERT line-by-line questions with Assertion-Reason"),
    PYQ_PRACTICE("PYQ Practice Test", "Official PYQs", "Authentic past-year questions from NEET, JEE, and Board exams"),
    FULL_LENGTH("Full-Length Exam", "Grand Mock", "Timed full syllabus simulation matching official exam pattern"),
    CUSTOM("Custom Test", "Personalized", "Customized question count, subjects, topics, and time limit"),
    AI_GENERATED("AI-Generated Test", "Adaptive AI", "Dynamic diagnostic generated by AI targeting your weak areas")
}

data class TestSection(
    val id: String,
    val name: String,
    val questionIndices: List<Int>
)

data class PerformanceBreakdown(
    val name: String,
    val correct: Int,
    val total: Int,
    val accuracyPercentage: Int,
    val score: Int
)

data class TestRecommendations(
    val conceptToRevise: String,
    val practiceQuestionsCount: Int = 20,
    val practiceTopic: String,
    val miniTestTitle: String,
    val retestPlan: String
)

data class DetailedTestAnalysis(
    val testId: String,
    val testTitle: String,
    val testCategory: TestType,
    val score: Int,
    val maximumMarks: Int,
    val accuracy: Int,
    val correctCount: Int,
    val incorrectCount: Int,
    val unattemptedCount: Int,
    val timeSpentSeconds: Int,
    val averageTimePerQuestionSeconds: Int,
    val predictedPercentile: Double,
    val predictedRank: String,
    val subjectPerformance: List<PerformanceBreakdown>,
    val chapterPerformance: List<PerformanceBreakdown>,
    val topicPerformance: List<PerformanceBreakdown>,
    val difficultyPerformance: List<PerformanceBreakdown>,
    val mistakePatterns: Map<MistakeType, Int>,
    val aiExplanation: String,
    val recommendations: TestRecommendations
)
